"""Virtual Sonar-style channels, built from PipeWire loopbacks.

Each channel is a sink apps can play into. Their outputs are mixed into
EasyEffects when it is running, otherwise into the current hardware sink.
Equalisation stays in EasyEffects — this graph only provides the channels.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import time

from .config import CONFIG_DIR, GRAPH_CONF, GRAPH_CONF_PATH, SINK_CHANNELS

HEADER = """# Generated by SonusDeck. Edits are overwritten when the graph restarts.
context.properties = {
    log.level = 0
}

context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}

context.modules = [
    { name = libpipewire-module-rt
        args = { nice.level = -11 }
        flags = [ ifexists nofail ]
    }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }
"""

FOOTER = "]\n"


def _loopback(channel) -> str:
    return f"""
    {{ name = libpipewire-module-loopback
        args = {{
            node.description = "{channel.description}"
            audio.position = [ FL FR ]
            capture.props = {{
                node.name        = "{channel.node_name}"
                node.description = "{channel.description}"
                media.class      = Audio/Sink
                node.virtual     = true
                priority.session = 0
                session.suspend-timeout-seconds = 0
            }}
            playback.props = {{
                node.name    = "output.{channel.node_name}"
                node.passive = true
                node.virtual = true
            }}
        }}
    }}
"""


def render_config() -> str:
    body = "".join(_loopback(channel) for channel in SINK_CHANNELS)
    return HEADER + body + FOOTER


def write_config() -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    GRAPH_CONF_PATH.write_text(render_config(), encoding="utf-8")


class GraphProcess:
    """Owns the `pipewire -c` child that provides the channels."""

    def __init__(self) -> None:
        self.proc: subprocess.Popen | None = None
        self.error = ""

    @staticmethod
    def available() -> bool:
        return shutil.which("pipewire") is not None

    def running(self) -> bool:
        return self.proc is not None and self.proc.poll() is None

    def start(self) -> bool:
        if self.running():
            return True
        if not self.available():
            self.error = "pipewire not found"
            return False
        write_config()
        env = dict(os.environ)
        env["PIPEWIRE_CONFIG_DIR"] = str(CONFIG_DIR)
        try:
            self.proc = subprocess.Popen(
                ["pipewire", "-c", GRAPH_CONF],
                env=env,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                start_new_session=True,
            )
        except OSError as exc:
            self.error = str(exc)
            return False
        deadline = time.monotonic() + 2.0
        while time.monotonic() < deadline:
            if not self.running():
                self.error = "graph exited immediately"
                return False
            if _channels_visible():
                self.error = ""
                return True
            time.sleep(0.1)
        self.error = ""
        return self.running()

    def stop(self) -> None:
        if not self.running():
            self.proc = None
            return
        assert self.proc is not None
        self.proc.terminate()
        try:
            self.proc.wait(timeout=2.0)
        except subprocess.TimeoutExpired:
            self.proc.kill()
        self.proc = None

    def restart(self) -> bool:
        self.stop()
        return self.start()


def _channels_visible() -> bool:
    try:
        out = subprocess.run(
            ["pactl", "list", "short", "sinks"],
            capture_output=True, text=True, timeout=2.0,
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return False
    return all(channel.node_name in out for channel in SINK_CHANNELS)
