"""Virtual Sonar-style channels, built from PipeWire loopbacks.

Each channel is a sink apps can play into. Their outputs are mixed into
EasyEffects when it is running, otherwise into the current hardware sink.
Equalisation stays in EasyEffects — this graph only provides the channels.
"""

from __future__ import annotations

import os
import shutil
import signal
import subprocess
import time
from pathlib import Path

from .config import CONFIG_DIR, GRAPH_CONF, GRAPH_CONF_PATH, SINK_CHANNELS

PID_PATH = CONFIG_DIR / "graph.pid"

HEADER = """# Generated by SonusDeck. Edits are overwritten when the graph restarts.
context.properties = {
    log.level = 0
}

context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}

context.modules = [
    { name = libpipewire-module-rt
        args = { nice.level = -11 }
        flags = [ ifexists nofail ]
    }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }
"""

FOOTER = "]\n"


def _loopback(channel) -> str:
    return f"""
    {{ name = libpipewire-module-loopback
        args = {{
            node.description = "{channel.description}"
            audio.position = [ FL FR ]
            capture.props = {{
                node.name        = "{channel.node_name}"
                node.description = "{channel.description}"
                media.class      = Audio/Sink
                node.virtual     = true
                priority.session = 0
                session.suspend-timeout-seconds = 0
            }}
            playback.props = {{
                node.name    = "output.{channel.node_name}"
                node.passive = true
                node.virtual = true
            }}
        }}
    }}
"""


def render_config() -> str:
    body = "".join(_loopback(channel) for channel in SINK_CHANNELS)
    return HEADER + body + FOOTER


def write_config() -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    GRAPH_CONF_PATH.write_text(render_config(), encoding="utf-8")


def _read_pid() -> int | None:
    try:
        return int(PID_PATH.read_text(encoding="utf-8").strip())
    except (OSError, ValueError):
        return None


def _pid_is_graph(pid: int) -> bool:
    try:
        cmdline = Path(f"/proc/{pid}/cmdline").read_bytes().replace(b"\x00", b" ").decode()
    except OSError:
        return False
    return "pipewire" in cmdline and GRAPH_CONF in cmdline


def _stop_pid(pid: int) -> None:
    try:
        os.kill(pid, signal.SIGTERM)
    except OSError:
        return
    for _ in range(20):
        try:
            os.kill(pid, 0)
        except OSError:
            return
        time.sleep(0.1)
    try:
        os.kill(pid, signal.SIGKILL)
    except OSError:
        pass


def _reap_stale() -> None:
    pid = _read_pid()
    if pid and _pid_is_graph(pid):
        _stop_pid(pid)
    try:
        out = subprocess.run(
            ["pgrep", "-f", f"pipewire -c {GRAPH_CONF}"],
            capture_output=True, text=True, timeout=2.0,
        ).stdout
    except (OSError, subprocess.SubprocessError):
        out = ""
    for item in out.split():
        try:
            extra = int(item)
        except ValueError:
            continue
        if extra != os.getpid() and _pid_is_graph(extra):
            _stop_pid(extra)
    PID_PATH.unlink(missing_ok=True)


class GraphProcess:
    """Owns the `pipewire -c` child that provides the channels."""

    def __init__(self) -> None:
        self.proc: subprocess.Popen | None = None
        self.error = ""

    @staticmethod
    def available() -> bool:
        return shutil.which("pipewire") is not None

    def running(self) -> bool:
        return self.proc is not None and self.proc.poll() is None

    def start(self) -> bool:
        if self.running():
            return True
        if not self.available():
            self.error = "pipewire not found"
            return False
        _reap_stale()
        write_config()
        env = dict(os.environ)
        env["PIPEWIRE_CONFIG_DIR"] = str(CONFIG_DIR)
        try:
            self.proc = subprocess.Popen(
                ["pipewire", "-c", GRAPH_CONF],
                env=env,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                start_new_session=True,
            )
        except OSError as exc:
            self.error = str(exc)
            return False
        PID_PATH.write_text(str(self.proc.pid), encoding="utf-8")
        deadline = time.monotonic() + 2.0
        while time.monotonic() < deadline:
            if not self.running():
                self.error = "graph exited immediately"
                return False
            if _channels_visible():
                self.error = ""
                return True
            time.sleep(0.1)
        self.error = ""
        return self.running()

    def stop(self) -> None:
        pid = self.proc.pid if self.running() else _read_pid()
        if self.running() and self.proc is not None:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=2.0)
            except subprocess.TimeoutExpired:
                self.proc.kill()
            self.proc = None
        elif pid and _pid_is_graph(pid):
            _stop_pid(pid)
        PID_PATH.unlink(missing_ok=True)

    def restart(self) -> bool:
        self.stop()
        return self.start()


def _channels_visible() -> bool:
    try:
        out = subprocess.run(
            ["pactl", "list", "short", "sinks"],
            capture_output=True, text=True, timeout=2.0,
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return False
    return all(channel.node_name in out for channel in SINK_CHANNELS)
